"""add comment media columns

Revision ID: 71c89152853f
Revises: 26bbe770b428
Create Date: 2026-05-22 06:26:14.610984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c89152853f'
down_revision: Union[str, Sequence[str], None] = '26bbe770b428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('audio_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'audio_url')
    op.drop_column('comments', 'image_url')
    # ### end Alembic commands ###
