"""add repost support

Revision ID: 74b7d2c847ba
Revises: 71c89152853f
Create Date: 2026-06-05 10:30:37.731704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b7d2c847ba'
down_revision: Union[str, Sequence[str], None] = '71c89152853f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('repost_of_post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'posts', ['repost_of_post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'repost_of_post_id')
    # ### end Alembic commands ###
